-- Rotate the guest access token for an order whose link leaked.
--
-- THE DEFECT
--
-- Security promises the remedy: "Admin can rotate a token if a link leaks"
-- (docs/security.md §6, repeated in §9 and docs/ux.md). Nothing implemented it.
-- A token is a bearer secret shown exactly once on the confirmation page; if
-- that page is forwarded, screenshotted or read off a shared phone, the link
-- keeps working for as long as the order exists. There was no way to revoke it:
-- the token is generated by the `gen_random_uuid()` column default at insert,
-- and `orders` is SELECT-only under RLS, so no admin path could write the row
-- either. The only recovery was to touch the database by hand.
--
-- WHY THIS SHAPE
--
-- Rotation is a write to `orders.access_token`, so like every other write to
-- the ledger tables it is a `security definer` RPC rather than a direct table
-- update (AGENTS.md rule 1). It is a single UPDATE, but the shape matters:
--
--   * The row is locked `for update` before anything is decided. Two admins
--     rotating at the same moment would otherwise each read the old token,
--     each mint a new one, and the second UPDATE would silently win while the
--     first admin copied a link that no longer works.
--   * `require_admin()` runs at entry, as every admin RPC must (security.md
--     §4); the definer context bypasses RLS, so the assertion is the guard.
--   * The new token is `gen_random_uuid()` — the same expression the column
--     default and `place_online_order` use. 122 bits of randomness, and it
--     inherits the unique index on `access_token`, so a collision would be
--     rejected rather than quietly serving two orders under one token.
--
-- THE TOKEN IS RETURNED EXACTLY ONCE, HERE
--
-- The new token appears in this function's return value and nowhere else. It
-- is deliberately NOT written to `order_status_history` or `inventory_movements`
-- — a rotation is neither a fulfilment transition nor a stock movement, and
-- those tables are readable by any admin and rendered in the interface, so a
-- token there would be the leak it is meant to repair. The callers that show
-- order lists and detail views never receive it: `rotate_order_access_token`
-- is the only function that reads a token out after creation, and only in
-- response to an explicit admin rotation.
--
-- WHY AN ORDER WITH NO TOKEN IS REFUSED RATHER THAN MINTED ONE
--
-- The `access_token` column is `not null default gen_random_uuid()`, so under
-- the current schema every row has one. The guard is still here because the
-- semantic is "replace the existing link", not "create a public link that
-- never existed": if the column is ever relaxed for channels that have no guest
-- page (an in-person sale has no confirmation link to leak), this function must
-- not become a way to publish a token for an order that was never public.
-- Refusing with a mapped code names the remedy instead of inventing a secret.

create or replace function public.rotate_order_access_token(p_order_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_order public.orders;
  v_token uuid;
begin
  perform public.require_admin();

  -- Lock the order so two rotations cannot interleave: without this the second
  -- UPDATE would overwrite the first token while the first admin was still
  -- copying it, and both would believe their link is the live one.
  select * into v_order from public.orders where id = p_order_id for update;
  if not found then
    raise exception 'order_not_found' using errcode = 'P0001';
  end if;

  -- See the header: replace an existing link, never mint one for an order that
  -- has none. An in-person sale has no guest page, so there is nothing to leak
  -- and nothing to rotate.
  if v_order.access_token is null then
    raise exception 'no_access_token' using errcode = 'P0001';
  end if;

  -- The same expression as the column default and place_online_order. `returning`
  -- gives the inserted value back so the function never re-reads the row.
  update public.orders
     set access_token = gen_random_uuid()
   where id = p_order_id
  returning access_token into v_token;

  return jsonb_build_object(
    'order_id', v_order.id,
    'order_number', v_order.order_number,
    'access_token', v_token
  );
end;
$$;

-- Every function here is executable by PUBLIC until told otherwise.
revoke execute on function public.rotate_order_access_token(uuid)
  from public, anon, authenticated;
grant execute on function public.rotate_order_access_token(uuid) to authenticated;
